
import type { Metadata } from "next";
import {Playfair_Display, Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const greatVibes = localFont({
  src: "../fonts/GreatVibes.ttf",
  variable: "--font-mi-fuente-1",
});


const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/xck4doz.css"/>
      </head>
      <body
        className={`${greatVibes.variable} ${playfair.variable} ${inter.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
